version: 0.2
phases:

 install:
   commands:
     - export DEBIAN_FRONTEND=noninteractive
     - apt-get update
     - apt-get install -y  software-properties-common
     - apt-get update
     - apt-get install -y php7.1
     - apt-get install php-xdebug
     - php -m
     - phpenmod xdebug 
     - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
     - php composer-setup.php ;
     - php -r "unlink('composer-setup.php');" ;
     - mv composer.phar /usr/local/bin/composer
     - php --ini
