version: 0.2
phases:

 install:
   commands:
     - rm -f /usr/local/bin/php*
     - rm -f /usr/local/bin/phar*
     - rm -f /usr/local/bin/pear*
     - rm -f /usr/local/bin/pecl*
     - apt-get update
     - apt-get upgrade -y
     - apt-get install -y php7.2-cli php7.2-zip
     - phpenmod zip
