version: 0.2
phases:

 install:
   commands:
     #Install required packages
     - |
         export DEBIAN_FRONTEND=noninteractive
         #Install php7.4.8
         apt-get update
         apt-get install -y  software-properties-common
         LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
         apt-get update
         apt-get install -y php7.4.8
         apt-get install php-xdebug
    
    #Enable xdebug - phpunit uses this for code coverage
         php -m
         phpenmod xdebug 
