version: 0.2
phases:

 install:
   commands:
     - rm -f /usr/local/bin/php*
     - rm -f /usr/local/bin/phar*
     - rm -f /usr/local/bin/pear*
     - rm -f /usr/local/bin/pecl*
     #- apt-get update
     #- apt-get upgrade -y
     - apt-get install -y php7.2-cli php7.2-zip php7.2-xdebug
     - phpenmod zip
     - apt-get install locate
     - updatedb
     - locate xdebug.so
     - php -m
     - phpenmod xdebug 
     - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
     - php composer-setup.php ;
     - php -r "unlink('composer-setup.php');" ;
     - mv composer.phar /usr/local/bin/composer
     - php --ini
     - sed '1 s/^/zend_extension = \/usr\/lib\/php\/20170718\/xdebug.so\n/' /root/.phpenv/versions/7.3.13/etc/php.ini
     - php -v
     - composer require composer/xdebug-handler
     - composer install
     - ./vendor/bin/phpunit --verbose -c phpunit.xml
     
